routes/web.php
<?php

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

/* MANAGE */ 

Route::namespace('Manage')->prefix('manage')->middleware(['auth','auth.admin'])->name('manage.')->group(function(){
    Route::resource('/users', 'UserController');
    Route::resource('/notices', 'NoticesController');
    Route::resource('/database', 'DataBController');
    Route::resource('/events', 'EventController');
    
    Route::get('/users/index/pdf', 'UserController@pdf');
    Route::get('/notices/index/pdf', 'NoticesController@pdf');
});

/* OPERATIONS */

Route::namespace('Operations')->prefix('operations')->middleware(['auth','auth.admin','auth.operations'])->name('operations.')->group(function(){
    Route::get('/bookings/{id}/invoice', 'BookingController@editvoice')->name('bookings.editvoice');
    Route::get('/bookings/{id}/confirmation', 'BookingController@editconfirm')->name('bookings.editconfirm');
    Route::post('/bookings/{id}/updatevoice', 'BookingController@updatevoice')->name('bookings.updatevoice');
    Route::post('/bookings/{id}/updateconfirm', 'BookingController@updateconfirm')->name('bookings.updateconfirm');
    Route::resource('/bookings', 'BookingController');

    Route::get('/bookings/index/pdf', 'BookingController@pdf');
});

/* CUSTOMERS */

Route::namespace('Customers')->prefix('customers')->middleware(['auth','auth.admin','auth.marketing'])->name('customers.')->group(function(){
    Route::resource('/won', 'CustomerController');
    Route::resource('/tasks', 'TasksController');
    Route::resource('/completed', 'CompleteController');
    Route::resource('/opportunities', 'OppController');
    Route::resource('/leads', 'LeadsController');

    Route::get('/opportunities/index/pdf', 'OppController@pdf');
    Route::get('/won/index/pdf', 'CustomerController@pdf');
    Route::get('/tasks/index/pdf', 'TasksController@pdf');
    Route::get('/completed/index/pdf', 'CompleteController@pdf');
    Route::get('/leads/index/pdf', 'LeadsController@pdf');

});

/* ACCOUNTS */

Route::namespace('Accounts')->prefix('accounts')->middleware(['auth','auth.admin','auth.accounts'])->name('accounts.')->group(function(){
    Route::resource('/payments', 'PaymentsController');
    Route::resource('/incomes', 'IncomeController');
    Route::resource('/loans', 'LoansController');
    Route::resource('/salaries', 'SalaryController');

    Route::get('/payments/index/pdf', 'PaymentsController@pdf');
    Route::get('/incomes/index/pdf', 'IncomeController@pdf');
    Route::get('/loans/index/pdf', 'LoansController@pdf');
});

/* EMPLOYEES */

Route::namespace('Employees')->prefix('employees')->middleware(['auth','auth.admin','auth.accounts'])->name('employees.')->group(function(){
    Route::resource('/staff', 'EmployeeController');
    Route::get('/staff/index/pdf', 'EmployeeController@pdf');
});

app/Http/Controllers/Customers/CompleteController.php
<?php

namespace App\Http\Controllers\Customers;
use App\Notes;
use App\Contact;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class CompleteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $taskNotes2 = Notes::where('Task_Status' , 'completed')->get(); 
        $contacts = Contact::all();
    
        return view('customers.completed.index',[
            'taskNotes2' => $taskNotes2,
            'contacts'=> $contacts,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $contacts = Contact::all();

        return view('customers.completed.create', compact('contacts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       // 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $taskNotes2 = Notes::find($id);
        return view('customers.completed.edit', compact('taskNotes2')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'Todo_Due_Date'=>'required|date',
            'description'=>'required',
            'Task_Status'=>'required',
            'Task_Update'=>'required',
            'Sales_Rep'=>'required',
        ]);

        $notes = Notes::find($id);
        $notes->description = $request->get('description');
        $notes->Todo_Due_Date  = $request->get('Todo_Due_Date');
        $notes->Task_Status  = $request->get('Task_Status');
        $notes->Task_Update  = $request->get('Task_Update');
        $notes->Sales_Rep = $request->get('Sales_Rep');
        $notes->save();

        return redirect()->route('customers.completed.index')->with('success', 'Task has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $notes = Notes::find($id);
        $notes->delete();

        return redirect()->route('customers.completed.index')->with('success', 'Task has been deleted.');
    }

    function get_com_data()
    {
        $com_data = Notes::where('Task_Status' , 'completed')->limit(10)->get();

        return $com_data;
    }

    function pdf()
    {
        $pdf = \App::make('dompdf.wrapper'); 
        $pdf->loadHTML($this->convert_com_data_to_html());
        return $pdf->stream();
    }

    function convert_com_data_to_html()
    {
        $com_data = $this->get_com_data(); 
        $output ='
            <h3 align="center">Completed Task Data</h3>
            <table width="100%" style="border-collapse: collapse; border: 0px;">
            
            <tr>
                <th style="border: 1px solid; padding:12px;">ID</th>
                <th style="border: 1px solid; padding:12px;" >Company</th>
                <th style="border: 1px solid; padding:12px;" >Task</th>
                <th style="border: 1px solid; padding:12px;" >Deadline</th>
                <th style="border: 1px solid; padding:12px;" >Update</th>
                <th style="border: 1px solid; padding:12px;" >Handler</th>
                <th style="border: 1px solid; padding:12px;" >Last Updated</th>
                
            </tr>
            
            ';  
            
            foreach($com_data as $com_data)
            {
            $output .= '   
            <tr>
                <td style="border: 1px solid; padding:12px;">'.$com_data->id.'</td>
                <td style="border: 1px solid; padding:12px;">'.$com_data->contact['Company'].'</td>
                <td style="border: 1px solid; padding:12px;">'.$com_data->description.'</td>
                <td style="border: 1px solid; padding:12px;">'.$com_data->Todo_Due_Date.'</td>
                <td style="border: 1px solid; padding:12px;">'.$com_data->Task_Update.'</td>
                <td style="border: 1px solid; padding:12px;">'.$com_data->Sales_Rep.'</td>
                <td style="border: 1px solid; padding:12px;">'.$com_data->updated_at.'</td>
              
            </tr>
            ';
            }
    $output .= '</table>';
    return $output;
    }
}

app/Http/Controllers/Customers/CustomerController.php
<?php

namespace App\Http\Controllers\Customers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Contact;

class CustomerController extends Controller
{
/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $wonContact = Contact::where('Status', 'won')->get();
        return view('customers.won.index',[
            'wonContact' => $wonContact,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customers.won.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $wonContact = Contact::find($id);
        return view('customers.won.edit', compact('wonContact'));  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'Contact_First'=>'required|String',
            'Contact_Last'=>'required|String',
            'Phone'=>'required|size:10',
            'Email'=>'required|email',
            'Company'=>'required',
            'Status'=>'required',
            'Project_Type'=>'required',
            'Project_Description'=>'required',
        ]);

        $contact = Contact::find($id);
        $contact->Contact_First =  $request->get('Contact_First');
        $contact->Contact_Last = $request->get('Contact_Last');
        $contact->Phone = $request->get('Phone');
        $contact->Email = $request->get('Email');
        $contact->Contact_Title = $request->get('Contact_Title');
        $contact->Title = $request->get('Title');
        $contact->Company = $request->get('Company');
        $contact->Status = $request->get('Status');
        $contact->Project_Type = $request->get('Project_Type');
        $contact->Project_Description = $request->get('Project_Description');
        $contact->Budget = $request->get('Budget');
        $contact->save();

        return redirect()->route('customers.won.index')->with('success', 'Contact updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Contact::find($id);
        $contact->delete();

        return redirect()->route('customers.won.index')->with('success', 'Contact deleted!');
    }

    function get_won_data()
    {
        $won_data = Contact::where('Status', 'won')->limit(10)->get();

        return $won_data;
    }

    function pdf()
    {
        $pdf = \App::make('dompdf.wrapper'); 
        $pdf->loadHTML($this->convert_won_data_to_html());
        return $pdf->stream();
    }

    function convert_won_data_to_html()
    {
        $won_data = $this->get_won_data(); 
        $output ='
            <h3 align="center">Won Data</h3>
            <table width="100%" style="border-collapse: collapse; border: 0px;">
            
            <tr>
                <th style="border: 1px solid; padding:12px;">Company</th>
                <th style="border: 1px solid; padding:12px;" >Topic</th>
                <th style="border: 1px solid; padding:12px;" >Contact Person</th>
                <th style="border: 1px solid; padding:12px;" >Handler</th>
                <th style="border: 1px solid; padding:12px;" >Phone Number</th>
                <th style="border: 1px solid; padding:12px;" >Email</th>
                <th style="border: 1px solid; padding:12px;" >Remarks</th>
               
               
            </tr>
            
            ';  
            
            foreach($won_data as $won_data)
            {
            $output .= '   
            <tr>
                <td style="border: 1px solid; padding:12px;">'.$won_data->Company.'</td>
                <td style="border: 1px solid; padding:12px;">'.$won_data->Project_Type.'</td>
                <td style="border: 1px solid; padding:12px;">'.$won_data->Contact_First.'</td>
                <td style="border: 1px solid; padding:12px;">'.$won_data->Sales_Rep.'</td>
                <td style="border: 1px solid; padding:12px;">'.$won_data->Phone.'</td>
                <td style="border: 1px solid; padding:12px;">'.$won_data->Email.'</td>
                <td style="border: 1px solid; padding:12px;">'.$won_data->Project_Description.'</td>
               
            </tr>
            ';
            }
    $output .= '</table>';
    return $output;
    }
}

resources/views/customers/opportunities/detailAdd.blade.php
@extends('layouts.app')

@section('content')
<div class="context-sidebar">
    <div class="nav-sidebar">
        <ul class="sidebar-top-level-items">

            <li class="">
                <a href="{{ route('customers.opportunities.index') }}">
                    <div class="nav-icon-container">
                        <i class="fa fa-home"></i>
                    </div>
                    <span class="nav-item-name">Opportunities</span>
                </a>
            </li>

            <li class="">
                <a href="{{ route('customers.leads.index') }}">
                    <div class="nav-icon-container">
                        <i class="fa fa-moon-o"></i>
                    </div>
                    <span class="nav-item-name">Leads</span>
                </a>
            </li>

            <li class="">
                <a href="{{ route('customers.won.index') }}">
                    <div class="nav-icon-container">
                        <i class="fa fa-flask"></i>
                    </div>
                    <span class="nav-item-name">Customers</span>
                </a>
            </li>

            <li class="">
                <a href="{{ route('customers.tasks.index') }}">
                    <div class="nav-icon-container">
                        <i class="fa fa-flask"></i>
                    </div>
                    <span class="nav-item-name">Tasks</span>
                </a>
            </li>

            <li class="">
                <a href="{{ route('customers.completed.index') }}">
                    <div class="nav-icon-container">
                        <i class="fa fa-flask"></i>
                    </div>
                    <span class="nav-item-name">Completed Tasks</span>
                </a>
            </li>

        </ul>
    </div>

    <div class="content-wrapper">

        <nav class="breadcrumbs container-fluid container-limited" role="navigation">
            <div class="breadcrumbs-container">
                <div class="breadcrumbs-links js-title-container">

                    <ul class="list-unstyled breadcrumbs-list js-breadcrumbs-list">

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Breadcrumbs One</a></div>
                            <span class="mid-b">></span>
                        </li>

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Breadcrumbs Two</a></div>
                            <span class="mid-b">></span>
                        </li>

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Bradcrumbs Three</a></div>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>

        <!------------------------------------------------------------------------->
        <div class="con-form" style="margin:20px 34px 0 34px">
            <div class="row">
                <div class="col">
                    <div>
                        @if ($errors->any())
                        <div class="alert alert-danger" style="padding:15px 0px 0px 0px">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        <form method="post" action="{{ route('customers.opportunities.store') }}">
                            @csrf
                            <div class="form-group">
                                <label for="Contact_First">First Name:</label>
                                <input type="text" class="form-control" name="Contact_First"
                                    value="{{ old('Contact_First') }}" />
                            </div>

                            <div class="form-group">
                                <label for="Contact_Last">Last Name:</label>
                                <input type="text" class="form-control" name="Contact_Last"
                                    value="{{ old('Contact_Last') }}" />
                            </div>

                            <div class="form-group">
                                <label for="Email">Email:</label>
                                <input type="text" class="form-control" name="Email" value="{{ old('Email') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Phone">Phone number:</label>
                                <input type="text" class="form-control" name="Phone" value="{{ old('Phone') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Date_of_Initial_Contact">Initial Contact:</label>
                                <input type="date" class="form-control" name="Date_of_Initial_Contact"
                                    value="{{ old('Date_of_Initial_Contact') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Company">Company:</label>
                                <input type="text" class="form-control" name="Company" value="{{ old('Company') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Address">Address No:</label>
                                <input type="text" class="form-control" name="Address" value="{{ old('Address') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Address_Street_1">Street:</label>
                                <input type="text" class="form-control" name="Address_Street_1"
                                    value="{{ old('Address_Street_1') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Address_City">City:</label>
                                <input type="text" class="form-control" name="Address_City"
                                    value="{{ old('Address_City') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Address_State">State:</label>
                                <input type="text" class="form-control" name="Address_State"
                                    value="{{ old('Address_State') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Address_Zip">Zip:</label>
                                <input type="text" class="form-control" name="Address_Zip"
                                    value="{{ old('Address_Zip') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Address_Country">Country:</label>
                                <input type="text" class="form-control" name="Address_Country"
                                    value="{{ old('Address_Country') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Status">Status:</label>
                                <select class="form-control" name="Status">
                                    <option value="opportunities">Opportunities</option>
                                    <option value="leads">Leads</option>
                                    <option value="won">Won</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="Sales_Rep">Handler:</label>
                                <input type="text" class="form-control" name="Sales_Rep"
                                    value="{{ old('Sales_Rep') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Project_Type">Topic:</label>
                                <input type="text" class="form-control" name="Project_Type"
                                    value="{{ old('Project_Type') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Project_Description">Remarks:</label>
                                <input type="text" class="form-control" name="Project_Description"
                                    value="{{ old('Project_Description') }}" />
                            </div>
                            <div class="form-group">
                                <label for="Proposal_Due_Date">Quotation Due Date:</label>
                                <input type="date" class="form-control" name="Proposal_Due_Date"
                                    value="{{ old('Proposal_Due_Date') }}" />
                            </div>

                            <input type="submit" class="btn btn-primary" style="margin-bottom: 20px" value="Submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>


        <!--------------------------------->
    </div>
</div>
@endsection

resources/views/customers/opportunities/index.blade.php
@extends('layouts.app')

@section('content')
<div class="context-sidebar">
    <div class="nav-sidebar">
    <ul class="sidebar-top-level-items">

<li class="">
    <a href="{{ route('customers.opportunities.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-home"></i>
        </div>
        <span class="nav-item-name">Opportunities</span>
    </a>
</li>

<li class="">
    <a href="{{ route('customers.leads.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-moon-o"></i>
        </div>
        <span class="nav-item-name">Leads</span>
    </a>
</li>

<li class="">
    <a href="{{ route('customers.won.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Customers</span>
    </a>
</li>

<li class="">
    <a href="{{ route('customers.tasks.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Tasks</span>
    </a>
</li>

<li class="">
    <a href="{{ route('customers.completed.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Completed Tasks</span>
    </a>
</li>

</ul>
    </div>

    <div class="content-wrapper">

        <nav class="breadcrumbs container-fluid container-limited" role="navigation">
            <div class="breadcrumbs-container">
                <div class="breadcrumbs-links js-title-container">

                    <ul class="list-unstyled breadcrumbs-list js-breadcrumbs-list">

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Breadcrumbs One</a></div>
                            <span class="mid-b">></span>
                        </li>

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Breadcrumbs Two</a></div>
                            <span class="mid-b">></span>
                        </li>

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Bradcrumbs Three</a></div>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>

        <div class="con-tab">

            <div>
                <a style="margin-bottom: 20px; float: right; padding: 2px 30px 2px 30px; font-size: 14px;" href="{{ route('customers.opportunities.create') }}" class="btn btn-primary">Add</a>
                <a style="margin-bottom: 20px; float: right; padding: 2px 30px 2px 30px; margin-right: 4px; font-size: 14px;" href="{{ url('customers/opportunities/index/pdf') }}" class="btn btn-danger">PDF</a>
            </div>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col" class="col-t-1">Company</th>
                        <th scope="col" class="col-t-1">Topic</th>
                        <th scope="col" class="col-t-1">Contact Person</th>
                        <th scope="col" class="col-t-1">Handler</th>
                        <th scope="col" class="col-t-1">Phone Number</th>
                        <th scope="col" class="col-t-1">Email</th>
                        <th scope="col" class="col-t-1">Quotation Date</th>
                        <th scope="col" class="col-t-1">Remarks</th>
                        <th scope="col" class="col-t-1">Status</th>
                        <th scope="col" class="col-t-1">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($oppContact as $oppContact)
                    <tr class="tr-t-1">
                        <td class="tr-t-nm">{{ $oppContact->Company }}</td>
                        <td class="tr-t-nm">{{ $oppContact->Project_Type }}</td>
                        <td class="tr-t-nm">{{ $oppContact->Contact_First }} {{ $oppContact->Contact_Last }}</td>
                        <td class="tr-t-nm">{{ $oppContact->Sales_Rep }}</td>
                        <td class="tr-t-nm">{{ $oppContact->Phone }}</td>
                        <td class="tr-t-nm">{{ $oppContact->Email }}</td>
                        <td class="tr-t-nm">{{ $oppContact->Proposal_Due_Date }}</td>
                        <td class="tr-t-nm">{{ $oppContact->Project_Description }}</td>
                        <td class="tr-t-nm">{{ $oppContact->Status }}</td>
                        <th>
                            <a href="{{ route('customers.opportunities.edit',$oppContact->id)}}" class="float-left">
                                <button>
                                    <i class="fa fa-pencil ico-tb"></i>
                                </button>
                            </a>
                            <form action="{{ route('customers.opportunities.destroy', $oppContact->id)}}" method="POST"
                                class="float-left">
                                @csrf {{ method_field('DELETE') }}
                                <button type="submit"><i class="fa fa-trash ico-tb-r"></i></button>
                            </form>
                        </th>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection