routes/web.php
<?php

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

/* MANAGE */ 

Route::namespace('Manage')->prefix('manage')->middleware(['auth','auth.admin'])->name('manage.')->group(function(){
    Route::resource('/users', 'UserController');
    Route::resource('/notices', 'NoticesController');
    Route::resource('/database', 'DataBController');
    Route::resource('/events', 'EventController');
    
    Route::get('/users/index/pdf', 'UserController@pdf');
    Route::get('/notices/index/pdf', 'NoticesController@pdf');
});

/* OPERATIONS */

Route::namespace('Operations')->prefix('operations')->middleware(['auth','auth.admin','auth.operations'])->name('operations.')->group(function(){
    Route::get('/bookings/{id}/invoice', 'BookingController@editvoice')->name('bookings.editvoice');
    Route::get('/bookings/{id}/confirmation', 'BookingController@editconfirm')->name('bookings.editconfirm');
    Route::post('/bookings/{id}/updatevoice', 'BookingController@updatevoice')->name('bookings.updatevoice');
    Route::post('/bookings/{id}/updateconfirm', 'BookingController@updateconfirm')->name('bookings.updateconfirm');
    Route::resource('/bookings', 'BookingController');

    Route::get('/bookings/index/pdf', 'BookingController@pdf');
});

/* CUSTOMERS */

Route::namespace('Customers')->prefix('customers')->middleware(['auth','auth.admin','auth.marketing'])->name('customers.')->group(function(){
    Route::resource('/won', 'CustomerController');
    Route::resource('/tasks', 'TasksController');
    Route::resource('/completed', 'CompleteController');
    Route::resource('/opportunities', 'OppController');
    Route::resource('/leads', 'LeadsController');

    Route::get('/opportunities/index/pdf', 'OppController@pdf');
    Route::get('/won/index/pdf', 'CustomerController@pdf');
    Route::get('/tasks/index/pdf', 'TasksController@pdf');
    Route::get('/completed/index/pdf', 'CompleteController@pdf');
    Route::get('/leads/index/pdf', 'LeadsController@pdf');

});

/* ACCOUNTS */

Route::namespace('Accounts')->prefix('accounts')->middleware(['auth','auth.admin','auth.accounts'])->name('accounts.')->group(function(){
    Route::resource('/payments', 'PaymentsController');
    Route::resource('/incomes', 'IncomeController');
    Route::resource('/loans', 'LoansController');
    Route::resource('/salaries', 'SalaryController');

    Route::get('/payments/index/pdf', 'PaymentsController@pdf');
    Route::get('/incomes/index/pdf', 'IncomeController@pdf');
    Route::get('/loans/index/pdf', 'LoansController@pdf');
});

/* EMPLOYEES */

Route::namespace('Employees')->prefix('employees')->middleware(['auth','auth.admin','auth.accounts'])->name('employees.')->group(function(){
    Route::resource('/staff', 'EmployeeController');
    Route::get('/staff/index/pdf', 'EmployeeController@pdf');
});

app/Salary.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Salary extends Model
{
    protected $fillable = [
        'date',
        'employee',
        'salary'  
    ];
}

app/Http/Controllers/Accounts/IncomeController.php
<?php

namespace App\Http\Controllers\Accounts;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Income;

use PDF;
use DB;

class IncomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('accounts.incomes.index')->with('incomes', Income::paginate(10)); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('accounts.incomes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'date'=>'required',
            'details'=>'required',
            'amount'=>'required|integer'
        ]);

        $income = new Income([
            'date' => $request->get('date'),
            'details' => $request->get('details'),
            'amount'=> $request->get('amount')
        ]);
        $income->save();
        return redirect()->route('accounts.incomes.index')->with('success','The entry has been stored.'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $income = Income::find($id);
        return view('accounts.incomes.edit', compact('income'));  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'date'=>'required',
            'details'=>'required',
            'amount'=>'required|integer'
        ]);

        $income = Income::find($id);
        $income->date =  $request->get('date');
        $income->details = $request->get('details');
        $income->amount = $request->get('amount');
        $income->save();

        return redirect()->route('accounts.incomes.index')->with('success','The entry has been updated.'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $income = Income::find($id);
        $income->delete();

        return redirect()->route('accounts.incomes.index')->with('success','Data has been deleted.'); 
    }

    function get_income_data()
    {
        $income_data = DB::table('incomes')->limit(10)->get();

        return $income_data;
    }

    function pdf()
    {
        $pdf = \App::make('dompdf.wrapper'); 
        $pdf->loadHTML($this->convert_income_data_to_html());
        return $pdf->stream();
    }

    function convert_income_data_to_html()
    {
        $income_data = $this->get_income_data(); 
        $output ='
            <h3 align="center">Incomes Data</h3>
            <table width="100%" style="border-collapse: collapse; border: 0px;">
            
            <tr>
                <th style="border: 1px solid; padding:12px;" width="10%">Date</th>
                <th style="border: 1px solid; padding:12px;" width="20%">Details</th>
                <th style="border: 1px solid; padding:12px;" width="10%">Amount</th>
            </tr>
            
            ';  
            
            foreach($income_data as $income_data)
            {
            $output .= '   
            <tr>
                <td style="border: 1px solid; padding:12px;">'.$income_data->date.'</td>
                <td style="border: 1px solid; padding:12px;">'.$income_data->details.'</td>
                <td style="border: 1px solid; padding:12px;">'.$income_data->amount.'</td>
            
            </tr>
            ';
            }
    $output .= '</table>';
    return $output;
    }
}

app/Http/Controllers/Accounts/LoansController.php
<?php

namespace App\Http\Controllers\Accounts;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Loan;

use PDF;
use DB;

class LoansController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('accounts.loans.index')->with('loans', Loan::paginate(10)); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('accounts.loans.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'date'=>'required', 
            'details'=>'required',
            'amount'=>'required|integer',
            'bank'=>'required',
            'due_date'=>'required',
            'status'=>'required'
        ]);

        $loan = new Loan([
            'date' => $request->get('date'),
            'details' => $request->get('details'),
            'amount' => $request->get('amount'),
            'bank' => $request->get('bank'),
            'due_date' => $request->get('due_date'),
            'status' => $request->get('status')
        ]);
        $loan->save();
        return redirect()->route('accounts.loans.index')->with('success','Loan has been stored.'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $loan = Loan::find($id);
        return view('accounts.loans.edit', compact('loan'));  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'date'=>'required', 
            'details'=>'required',
            'amount'=>'required|integer',
            'bank'=>'required',
            'due_date'=>'required',
            'status'=>'required'
        ]);

        $loan = Loan::find($id);
        $loan->date =  $request->get('date');
        $loan->details =  $request->get('details');
        $loan->amount =  $request->get('amount');
        $loan->bank = $request->get('bank');
        $loan->due_date = $request->get('due_date');
        $loan->status = $request->get('status');
        $loan->save();

        return redirect()->route('accounts.loans.index')->with('success','Loan has been updated.'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $loan = Loan::find($id);
        $loan->delete();

        return redirect()->route('accounts.loans.index')->with('success','Loan has been deleted.'); 
    }

    function get_loans_data()
    {
        $loans_data = DB::table('loans')->limit(10)->get();

        return $loans_data;
    }

    function pdf()
    {
        $pdf = \App::make('dompdf.wrapper'); 
        $pdf->loadHTML($this->convert_loans_data_to_html());
        return $pdf->stream();
    }

    function convert_loans_data_to_html()
    {
        $loans_data = $this->get_loans_data(); 
        $output ='
            <h3 align="center">Loans Data</h3>
            <table width="100%" style="border-collapse: collapse; border: 0px;">
            
            <tr>
                <th style="border: 1px solid; padding:12px;" width="10%">Date</th>
                <th style="border: 1px solid; padding:12px;" width="20%">Details</th>
                <th style="border: 1px solid; padding:12px;" width="10%">Amount</th>
                <th style="border: 1px solid; padding:12px;" width="10%">Bank</th>
                <th style="border: 1px solid; padding:12px;" width="10%">Due Date</th>
                <th style="border: 1px solid; padding:12px;" width="10%">Status</th>
                
            </tr>
            
            ';  
            
            foreach($loans_data as $loans_data)
            {
            $output .= '   
            <tr>
                <td style="border: 1px solid; padding:12px;">'.$loans_data->date.'</td>
                <td style="border: 1px solid; padding:12px;">'.$loans_data->details.'</td>
                <td style="border: 1px solid; padding:12px;">'.$loans_data->amount.'</td>
                <td style="border: 1px solid; padding:12px;">'.$loans_data->bank.'</td>
                <td style="border: 1px solid; padding:12px;">'.$loans_data->due_date.'</td>
                <td style="border: 1px solid; padding:12px;">'.$loans_data->status.'</td>
            </tr>
            ';
            }
    $output .= '</table>';
    return $output;
    }
}

app/Http/Controllers/Accounts/PaymentsController.php
<?php

namespace App\Http\Controllers\Accounts;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Payment;

use PDF;
use DB;

class PaymentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('accounts.payments.index')->with('payments', Payment::paginate(10)); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('accounts.payments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'date'=>'required',
            'details'=>'required',
            'amount'=>'required|integer'
        ]);

        $payment = new Payment([
            'date' => $request->get('date'),
            'details' => $request->get('desc'),
            'amount'=> $request->get('payment')
        ]);
        $payment->save();
        return redirect()->route('accounts.payments.index')->with('success','Payment has been stored.'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $payment = Payment::find($id);
        return view('accounts.payments.edit', compact('payment'));  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'date'=>'required',
            'details'=>'required',
            'amount'=>'required|integer'
        ]);

        $payment = Payment::find($id);
        $payment->date =  $request->get('date');
        $payment->details = $request->get('details');
        $payment->amount = $request->get('amount');
        $payment->save();

        return redirect()->route('accounts.payments.index')->with('success','Payment has been updated.'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $payment = Payment::find($id);
        $payment->delete();

        return redirect()->route('accounts.payments.index')->with('success','Payment has been deleted.'); 
    }

    function get_payment_data()
    {
        $payment_data = DB::table('payments')->limit(10)->get();

        return $payment_data;
    }

    function pdf()
    {
        $pdf = \App::make('dompdf.wrapper'); 
        $pdf->loadHTML($this->convert_payment_data_to_html());
        return $pdf->stream();
    }

    function convert_payment_data_to_html()
    {
        $payment_data = $this->get_payment_data(); 
        $output ='
            <h3 align="center">Loans Data</h3>
            <table width="100%" style="border-collapse: collapse; border: 0px;">
            
            <tr>
                <th style="border: 1px solid; padding:12px;" width="10%">Date</th>
                <th style="border: 1px solid; padding:12px;" width="50%">Description</th>
                <th style="border: 1px solid; padding:12px;" width="10%">Amount</th>
               
            </tr>
            
            ';  
            
            foreach($payment_data as $payment_data)
            {
            $output .= '   
            <tr>
                <td style="border: 1px solid; padding:12px;">'.$payment_data->date.'</td>
                <td style="border: 1px solid; padding:12px;">'.$payment_data->details.'</td>
                <td style="border: 1px solid; padding:12px;">'.$payment_data->amount.'</td>
        
            </tr>
            ';
            }
    $output .= '</table>';
    return $output;
    }
}

resources/views/Accounts/Salaries/create.blade.php
@extends('layouts.app')

@section('content')
<div class="context-sidebar">
<div class="nav-sidebar">
<ul class="sidebar-top-level-items">

<li class="">
    <a href="{{ route('accounts.incomes.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-home"></i>
        </div>
        <span class="nav-item-name">Incomes</span>
    </a>
</li>

<li class="">
    <a href="{{ route('accounts.loans.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-moon-o"></i>
        </div>
        <span class="nav-item-name">Loans</span>
    </a>
</li>

<li class="">
    <a href="{{ route('accounts.payments.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Payments</span>
    </a>
</li>

<li class="">
    <a href="{{ route('accounts.salaries.index') }}"">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Salaries</span>
    </a>
</li>

<li class="">
    <a href="/">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Reports</span>
    </a>
</li>

</ul>
</div>

    <div class="content-wrapper">

        <nav class="breadcrumbs container-fluid container-limited" role="navigation">
            <div class="breadcrumbs-container">
                <div class="breadcrumbs-links js-title-container">

                    <ul class="list-unstyled breadcrumbs-list js-breadcrumbs-list">

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Breadcrumbs One</a></div>
                            <span class="mid-b">></span>
                        </li>

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Breadcrumbs Two</a></div>
                            <span class="mid-b">></span>
                        </li>

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Bradcrumbs Three</a></div>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>
        
        <div class="con-form" style="margin:20px 34px 0 34px">
        <div class="row">
            <div class="col">
                <div>
                    @if ($errors->any())
                    <div class="alert alert-danger" style="padding:15px 0px 0px 0px">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form method="post" action="{{ route('accounts.salaries.store') }}">
                        @csrf
                        
                        <div class="form-group">
                            <label for="salary">Salary :</label>
                            <input type="text" class="form-control" name="salary" />
                        </div>

                        <input type="submit" class="btn btn-primary" value="Submit">
                    </form>
                </div>
            </div>
        </div>
        </div>

    </div>
</div>
@endsection

resources/views/Accounts/Salaries/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="context-sidebar">
    <div class="nav-sidebar">
    <ul class="sidebar-top-level-items">

<li class="">
    <a href="{{ route('accounts.incomes.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-home"></i>
        </div>
        <span class="nav-item-name">Incomes</span>
    </a>
</li>

<li class="">
    <a href="{{ route('accounts.loans.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-moon-o"></i>
        </div>
        <span class="nav-item-name">Loans</span>
    </a>
</li>

<li class="">
    <a href="{{ route('accounts.payments.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Payments</span>
    </a>
</li>

<li class="">
    <a href="{{ route('accounts.salaries.index') }}"">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Salaries</span>
    </a>
</li>

<li class="">
    <a href="/">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Reports</span>
    </a>
</li>

</ul>
    </div>

    <div class="content-wrapper">

        <nav class="breadcrumbs container-fluid container-limited" role="navigation">
            <div class="breadcrumbs-container">
                <div class="breadcrumbs-links js-title-container">

                    <ul class="list-unstyled breadcrumbs-list js-breadcrumbs-list">

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Breadcrumbs One</a></div>
                            <span class="mid-b">></span>
                        </li>

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Breadcrumbs Two</a></div>
                            <span class="mid-b">></span>
                        </li>

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Bradcrumbs Three</a></div>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>
        
        <div class="con-form" style="margin:20px 34px 0 34px">
        <div class="row">
            <div class="col">
                <div>
                    @if ($errors->any())
                    <div class="alert alert-danger" style="padding:15px 0px 0px 0px">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form method="post" action="{{ route('accounts.salaries.update', ['salary' => $salary->id]) }}">
                    @method('PATCH') 
                    @csrf
                        <div class="form-group">
                            <label for="salary">Salary :</label>
                            <input type="text" class="form-control" name="salary" value={{ $salary->salary }} />
                        </div>

                        <input type="submit" class="btn btn-primary" value="Update">
                    </form>
                </div>
            </div>
        </div>
        </div>

    </div>
</div>

@endsection

resources/views/Accounts/Salaries/index.blade.php
@extends('layouts.app')

@section('content')
<div class="context-sidebar">
    <div class="nav-sidebar">
    <ul class="sidebar-top-level-items">

<li class="">
    <a href="{{ route('accounts.incomes.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-home"></i>
        </div>
        <span class="nav-item-name">Incomes</span>
    </a>
</li>

<li class="">
    <a href="{{ route('accounts.loans.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-moon-o"></i>
        </div>
        <span class="nav-item-name">Loans</span>
    </a>
</li>

<li class="">
    <a href="{{ route('accounts.payments.index') }}">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Payments</span>
    </a>
</li>

<li class="">
    <a href="{{ route('accounts.salaries.index') }}"">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Salaries</span>
    </a>
</li>

<li class="">
    <a href="/">
        <div class="nav-icon-container">
            <i class="fa fa-flask"></i>
        </div>
        <span class="nav-item-name">Reports</span>
    </a>
</li>

</ul>
    </div>

    <div class="content-wrapper">

        <nav class="breadcrumbs container-fluid container-limited" role="navigation">
            <div class="breadcrumbs-container">
                <div class="breadcrumbs-links js-title-container">
                    
                    <ul class="list-unstyled breadcrumbs-list js-breadcrumbs-list">

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Breadcrumbs One</a></div>
                            <span class="mid-b">></span>
                        </li>

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Breadcrumbs Two</a></div>
                            <span class="mid-b">></span>
                        </li>

                        <li>
                            <div class="breadcrumbs-sub-title"><a href="/">Bradcrumbs Three</a></div>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>

        <div class="con-tab">

        <div>
    <a style="margin-bottom: 20px; float: right; padding: 2px 30px 2px 30px; font-size: 14px;" href="{{ route('accounts.salaries.create')}}" class="btn btn-primary">Add</a>
    </div>  
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col" class="col-t-1">Date</th>
                        <th scope="col" class="col-t-1">Updated</th>
                        <th scope="col" class="col-t-1">Salary</th>
                        <th scope="col" class="col-t-1">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($salaries as $salary)
                    <tr class="tr-t-1">
                        <td class="tr-t-nm">{{ $salary->created_at }}</td>
                        <td class="tr-t-nm">{{ $salary->updated_at }}</td>
                        <td class="tr-t-nm">{{ $salary->salary }}</td>
                        <th>
                        <a href="{{ route('accounts.salaries.edit', $salary->id) }}" class="float-left">
                                <button>
                                    <i class="fa fa-pencil ico-tb"></i>
                                </button>
                            </a>
                            <form action="{{ route('accounts.salaries.destroy', $salary->id) }}" method="POST"
                                class="float-left">
                                @csrf {{ method_field('DELETE') }}
                                <button type="submit"><i class="fa fa-trash ico-tb-r"></i></button>
                            </form>
                        </th>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    </div>
</div>
@endsection